server:
  servlet:
    context-path: /dev
  port: 8083

#是否开启参数验证  开启：1  关闭：0
#isValidated: 1

#日志,日志级别： DEBUG<INFO<WARN<ERROR<FATAL
logging:
  level:
    org.clm.demo: info
  path: ./springbootdemo/logs/dev  #日志打印路径
  #file:
  config: classpath:log/logback-dev.xml #可以根据不同的环境指定不同的xml配置文件
